resources:
  - name: git-pipeline
    type: git
    source:
      uri: "https://github.com/Gauravambartani1/concourse.git"
      branch: main

jobs:
  - name: scrape-reliance-data
    plan:
      - get: git-pipeline
        trigger: true
      - task: scrape-task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: vault
              tag: 1.13.3
          outputs:
            - name: output-data
          run:
            path: sh
            args:
 
              - -c
              - |
                export VAULT_ADDR='http://192.168.3.55:8200'
                export VAULT_TOKEN='root-token'
                email=$(vault kv get -field = email secret/data/my-secrets)
                password=$(vault kv get -field = password secret/data/my-secrets)
                echo "export EMAIL=$email" > output-data/secrets.sh
                echo "export PASSWORD=$password" >> output-data/secrets.sh
                chmod +x output-data/secrets.sh
                ls -l output-data
                cat output-data/secrets.sh
